import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-zinc-200 dark:border-zinc-800 bg-white/70 dark:bg-black/50 backdrop-blur">
          <nav className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 h-14 flex items-center justify-between">
            <a href="/" className="font-semibold text-zinc-900 dark:text-zinc-100">PuzzLing.io</a>
            <div className="flex items-center gap-4 text-sm">
              <a href="/learn" className="text-zinc-700 hover:text-black dark:text-zinc-300 dark:hover:text-white">Learn</a>
              <a href="/games" className="text-zinc-700 hover:text-black dark:text-zinc-300 dark:hover:text-white">Games</a>
              <a href="/classroom" className="text-zinc-700 hover:text-black dark:text-zinc-300 dark:hover:text-white">Classroom</a>
              <a href="/community" className="text-zinc-700 hover:text-black dark:text-zinc-300 dark:hover:text-white">Community</a>
              <a href="/cool-links" className="text-zinc-700 hover:text-black dark:text-zinc-300 dark:hover:text-white">Links</a>
              <a href="/profile" className="text-zinc-700 hover:text-black dark:text-zinc-300 dark:hover:text-white">Profile</a>
            </div>
          </nav>
        </header>
        <main className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
